<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240322144133 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE animal_habitat_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_file_name VARCHAR(255) NOT NULL, habitat_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B00AD114AFFE2D26 ON animal_habitat_image (habitat_id)');
        $this->addSql('ALTER TABLE animal_habitat_image ADD CONSTRAINT FK_B00AD114AFFE2D26 FOREIGN KEY (habitat_id) REFERENCES animal_habitat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE animal_habitat_image DROP CONSTRAINT FK_B00AD114AFFE2D26');
        $this->addSql('DROP TABLE animal_habitat_image');
    }
}
